source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-sass-converter", "~> 2.0"
gem "just-the-docs", "~> 0.8.0"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
end
